#! /usr/bin/env bash

APP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

if [ -z "$GITHUB_PAT" ]
then
  echo "No Personal Access Token found in env var GITHUB_PAT"
  exit 1
fi

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PAYLOAD=$(uuidgen)
DATA="{\"ref\":\"${BRANCH_NAME}\", \"payload\": \"${PAYLOAD}\", \"description\": \"Deploy of branch $BRANCH_NAME\"}"

curl -sS --request POST \
  -H "Authorization: token $GITHUB_PAT" \
  --data "$DATA" \
  https://api.github.com/repos/jar349/pyslackops/deployments | jq '.id' | tee "$APP_DIR/.latest-deploy.id"

if [ "$?" -eq "0" ]
then
  DEPLOY_ID=$(cat $APP_DIR/script/latest-deploy.id)
  echo "Deployment created with ID $DEPLOY_ID and payload $PAYLOAD"
else
  echo "Failed to create deployment"
fi
