name: Deploy
on: [deployment]
jobs:
  build:
    name: Docker Packaging
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Package Registry
        run: docker login -u jar349 -p ${{ secrets.DEPLOYMENT_GITHUB_PAT }} docker.pkg.github.com
      - name: Build Docker Image
        run: docker built -t docker.pkg.github.com/jar349/pyslackops:${{ github.sha }} .
      - name: Upload Docker Image
        run: docker push docker.pkg.github.com/jar349/pyslackops:${{ github.sha }}
  prepare:
    name: Start new pyslackops Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Write out deployer SSH key
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.DEPLOYER_SSH_KEY }} > ~/.ssh/id_rsa
      - name: Stop and remove existing pyslackkops container
        run: ssh deployer@ruiz.house docker stop pyslackops; docker rm pyslackops
      - name: Start new pyslackops container
        run: |
          docker login -u jar349 -p ${{ secrets.DEPLOYMENT_GITHUB_PAT }} docker.pkg.github.com
          ssh deployer@ruiz.house docker run --name pyslackops --detaach --network --main --restart always -e "PBOT_SLACK_TOKEN=${{ secrets.PBOT_SLACK_TOKEN }}" docker.pkg.github.com/jar349/pyslackops:${{ github.sha }}


